---
    output: black_young.json
    epochs: 100
    trainsize: 30000
    testsize: 1000
    batch_size: 32
    num_workers: 2
    print_priors: True
    protected_attr: Black
    prediction_attr: Young
    checkpoint: by_checkpoint.pt
    retrain: False
    models:
        - random
        - adversarial
    random:
        checkpoint: by_random_checkpoint.pt
    adversarial:
        epochs: 10
        critic_steps: 300
        actor_steps: 100
        lambda: 0.75
        checkpoint: by_adversarial_checkpoint.pt