---
    epochs: 100
    trainsize: -1
    testsize: -1
    batch_size: 32
    num_workers: 4
    print_priors: True
    protected_attr: Black
    prediction_attr: Young
    checkpoint: checkpoint.pt
    models:
        - random
        - adversarial
    random:
        checkpoint: random_checkpoint.pt
    adversarial:
        epochs: 10
        critic_steps: 300
        actor_steps: 100
        lambda: 0.75
        checkpoint: adversarial_checkpoint.pt